"""
Canonical physics domain models for Project Nebula.

These models establish the resource-transformation foundation while the
legacy identity-vector system remains operational as the current emergent
identity implementation.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Dict, List, Literal, Optional


ResourceFlowType = Literal["consumed", "produced", "accumulated", "transferred"]


@dataclass(frozen=True)
class Resource:
    """A transferable capacity, not an identity or goal."""

    key: str
    label: str
    description: str
    unit: str = "relative"

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass(frozen=True)
class ResourceFlow:
    """A directional movement of one resource within a transformation."""

    resource: str
    amount: float
    flow_type: ResourceFlowType
    confidence: float = 1.0

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass(frozen=True)
class ResourceTransformation:
    """
    Resource input/output metadata generated by a signal.

    In this phase inference is intentionally conservative and rule-based.
    Manual payload metadata can later override or enrich these flows.
    """

    transformation_id: str
    source_signal_id: str
    consumes: List[ResourceFlow] = field(default_factory=list)
    produces: List[ResourceFlow] = field(default_factory=list)
    transfers: List[ResourceFlow] = field(default_factory=list)
    accumulates: List[ResourceFlow] = field(default_factory=list)
    inference_status: str = "rule_based_foundation"

    def to_dict(self) -> dict:
        return {
            "transformation_id": self.transformation_id,
            "source_signal_id": self.source_signal_id,
            "consumes": [flow.to_dict() for flow in self.consumes],
            "produces": [flow.to_dict() for flow in self.produces],
            "transfers": [flow.to_dict() for flow in self.transfers],
            "accumulates": [flow.to_dict() for flow in self.accumulates],
            "inference_status": self.inference_status,
        }


@dataclass(frozen=True)
class Trajectory:
    """A recurring pattern of resource transformations."""

    key: str
    label: str
    description: str
    resource_pattern: Dict[str, List[str]] = field(default_factory=dict)
    linked_identity_field: Optional[str] = None

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass(frozen=True)
class SignalDrift:
    """Immediate displacement generated by one processed signal."""

    magnitude: float
    dynamic_pull: float
    dominant_trajectory: str
    dominant_attractor: str
    vector_space: str

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass(frozen=True)
class IdentityDrift:
    """Accumulated displacement of the emergent identity state through time."""

    global_dominant_identity: str
    global_dominance: Dict[str, float]
    accumulated_vector_dimension: int
    derived_from: str = "aggregated_signal_drift"

    def to_dict(self) -> dict:
        return asdict(self)


RESOURCE_REGISTRY: Dict[str, Resource] = {
    "time": Resource("time", "Time", "Finite chronological capacity spent or reserved.", "minutes"),
    "energy": Resource("energy", "Energy", "Physical and cognitive activation capacity."),
    "attention": Resource("attention", "Attention", "Directed focus available for behavior."),
    "money": Resource("money", "Money", "Liquid economic capacity.", "currency"),
    "knowledge": Resource("knowledge", "Knowledge", "Reusable learned models, skills, and information."),
    "relationships": Resource("relationships", "Relationships", "Social trust, access, and connection capacity."),
    "health_capacity": Resource("health_capacity", "Health Capacity", "Embodied resilience and physical capacity."),
}


DEFAULT_TRAJECTORIES: Dict[str, Trajectory] = {
    "entrepreneurship": Trajectory(
        key="entrepreneurship",
        label="Entrepreneurship",
        description="Transforms time, energy, attention, money, knowledge, and relationships into business capacity.",
        resource_pattern={
            "consumes": ["time", "energy", "attention", "money"],
            "produces": ["money", "knowledge", "relationships"],
        },
    ),
    "engineering": Trajectory(
        key="engineering",
        label="Engineering",
        description="Transforms time and attention into technical knowledge, systems, and execution capacity.",
        resource_pattern={
            "consumes": ["time", "attention", "energy"],
            "produces": ["knowledge", "relationships"],
        },
        linked_identity_field="engineering",
    ),
    "language_fluency": Trajectory(
        key="language_fluency",
        label="Language Fluency",
        description="Transforms time and attention into language knowledge and communication range.",
        resource_pattern={
            "consumes": ["time", "attention"],
            "produces": ["knowledge", "relationships"],
        },
        linked_identity_field="be_fluent",
    ),
    "employment": Trajectory(
        key="employment",
        label="Employment",
        description="Transforms time and energy into money, knowledge, and relationships.",
        resource_pattern={
            "consumes": ["time", "energy"],
            "produces": ["money", "knowledge", "relationships"],
        },
    ),
    "health": Trajectory(
        key="health",
        label="Health",
        description="Transforms time and effort into energy and health capacity.",
        resource_pattern={
            "consumes": ["time", "energy"],
            "produces": ["energy", "health_capacity"],
        },
        linked_identity_field="fitness",
    ),
}


def resources_payload() -> dict:
    return {key: resource.to_dict() for key, resource in RESOURCE_REGISTRY.items()}


def trajectories_payload() -> dict:
    return {key: trajectory.to_dict() for key, trajectory in DEFAULT_TRAJECTORIES.items()}


def resolve_trajectory(category: str, dominant_attractor: str, action_text: str = "") -> str:
    """Map current legacy signal context onto the new trajectory layer."""
    text = action_text.lower()

    if dominant_attractor == "engineering" or category == "Work":
        if any(term in text for term in ("supplier", "lease", "profit", "shop", "business", "customer")):
            return "entrepreneurship"
        return "engineering"
    if dominant_attractor == "be_fluent" or category == "Education":
        return "language_fluency"
    if dominant_attractor == "fitness" or category == "Health":
        return "health"
    if category in {"Distraction", "Void"}:
        return "unstructured_drain"
    if any(term in text for term in ("job", "employment", "salary", "client", "meeting")):
        return "employment"
    return "unclassified"


def infer_resource_transformation(
    event_id: str,
    action_text: str,
    category: str,
    duration: int,
    dominant_trajectory: str,
    effort: float,
    result_value=None,
) -> ResourceTransformation:
    """Create foundational resource metadata for a signal."""
    confidence = 0.55
    minutes = float(max(duration, 0))
    effort_amount = round(max(effort, 0.0), 4)

    consumes = [
        ResourceFlow("time", minutes, "consumed", confidence),
        ResourceFlow("attention", effort_amount, "consumed", confidence),
    ]
    produces: List[ResourceFlow] = []
    accumulates: List[ResourceFlow] = []

    if dominant_trajectory == "engineering":
        produces.append(ResourceFlow("knowledge", effort_amount, "produced", confidence))
    elif dominant_trajectory == "language_fluency":
        produces.append(ResourceFlow("knowledge", effort_amount, "produced", confidence))
    elif dominant_trajectory == "health":
        consumes = [ResourceFlow("time", minutes, "consumed", confidence)]
        produces.extend([
            ResourceFlow("energy", round(effort_amount * 0.8, 4), "produced", confidence),
            ResourceFlow("health_capacity", effort_amount, "produced", confidence),
        ])
    elif dominant_trajectory == "employment":
        consumes.extend([ResourceFlow("energy", effort_amount, "consumed", confidence)])
        produces.extend([
            ResourceFlow("money", 0.0, "produced", confidence),
            ResourceFlow("knowledge", round(effort_amount * 0.5, 4), "produced", confidence),
            ResourceFlow("relationships", round(effort_amount * 0.3, 4), "produced", confidence),
        ])
    elif dominant_trajectory == "entrepreneurship":
        consumes.extend([ResourceFlow("energy", effort_amount, "consumed", confidence)])
        produces.extend([
            ResourceFlow("money", float(result_value or 0.0), "produced", confidence),
            ResourceFlow("knowledge", round(effort_amount * 0.6, 4), "produced", confidence),
            ResourceFlow("relationships", round(effort_amount * 0.4, 4), "produced", confidence),
        ])
    elif dominant_trajectory == "unstructured_drain":
        consumes.extend([ResourceFlow("energy", effort_amount, "consumed", confidence)])
    else:
        accumulates.append(ResourceFlow("knowledge", 0.0, "accumulated", 0.25))

    if result_value is not None and float(result_value) > 0:
        accumulates.append(ResourceFlow("knowledge", float(result_value), "accumulated", confidence))

    return ResourceTransformation(
        transformation_id=f"rt_{event_id}",
        source_signal_id=event_id,
        consumes=consumes,
        produces=produces,
        accumulates=accumulates,
    )


def empty_coherence_foundation() -> dict:
    return {
        "status": "placeholder",
        "definition": "Coherence measures alignment between resource flows across trajectories.",
        "score": None,
        "resource_flow_alignment": {},
        "trajectory_tensions": {},
        "todo": "TODO(coherence): compute convergence/divergence between consumed and produced resources across active trajectories.",
    }
